### ISSUE TITLE
Supervisor: Fails to connect when `http_proxy` is set

### ISSUE THREAD

**Issue by jsbyysheng** [posit-dev/positron#5481]
#### Positron and OS details:

Positron Version: 2024.12.0 build 41
Code - OSS Version: 1.93.0
Commit: 39536c265d6828a68291984d0d359170316d055e
Date: 2024-11-18T02:42:16.243Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 5.15.0-126-generic

#### Interpreter details:

Any version R or Python

## Describe the issue:

CONSOLE cannot be used, I got `HTTP request failed`.

![Image](https://github.com/user-attachments/assets/8ed57d2a-4411-4050-b0c6-be9cb784b9d4)

**Comment by jsbyysheng** [comment]
To add, I have the same issue on another Ubuntu 22.04 workstation, but the same version of Positron works fine on macOS.

**Comment by jsbyysheng** [comment]
## System details:

#### Positron and OS details:

Positron Version: 2024.12.0 build 41
Code - OSS Version: 1.93.0
Commit: 39536c265d6828a68291984d0d359170316d055e
Date: 2024-11-18T02:42:16.243Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-40-generic

#### Interpreter details:

Any version R or Python

## Describe the issue:

CONSOLE cannot be used, I got `HTTP request failed`.

In OUTPUT -> Terminal 
```
2024-11-26 13:59:29.881 [debug] Switching back to normal keypad. []
2024-11-26 13:59:29.881 [debug] CommandDetectionCapability#setCommandLine ["/bin/python3 /usr/share/positron/resources/app/extensions/positron-python/python_files/printEnvVariablesToFile.py /usr/share/positron/resources/app/extensions/positron-python/python_files/deactivate/zsh/envVars.txt",true]
2024-11-26 13:59:29.882 [debug] CommandDetectionCapability#handleCommandExecuted [0,6]
2024-11-26 13:59:29.882 [debug] parsing data "" [[]]
2024-11-26 13:59:29.972 [debug] parsing data "Traceback (most recent call last):
  File "/usr/share/positron/resources/app/extensions/positron-python/python_files/printEnvVariablesToFile.py", line 10, in <module>
    with open(output_file, "w") as outfile:  # noqa: PTH123
PermissionError: [Errno 13] Permission denied: '/usr/share/positron/resources/app/extensions/positron-python/python_files/deactivate/zsh/envVars.txt'
" [[84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,58,13,10,32,32,70,105,108,101,32,34,47,117,115,114,47,115,104,97,114,101,47,112,111,115,105,116,114,111,110,47,114,101,115,111,117,114,99,101,115,47,97,112,112,47,101,120,116,101,110,115,105,111,110,115,47,112,111,115,105,116,114,111,110,45,112,121,116,104,111,110,47,112,121,116,104,111,110,95,102,105,108,101,115,47,112,114,105,110,116,69,110,118,86,97,114,105,97,98,108,101,115,84,111,70,105,108,101,46,112,121,34,44,32,108,105,110,101,32,49,48,44,32,105,110,32,60,109,111,100,117,108,101,62,13,10,32,32,32,32,119,105,116,104,32,111,112,101,110,40,111,117,116,112,117,116,95,102,105,108,101,44,32,34,119,34,41,32,97,115,32,111,117,116,102,105,108,101,58,32,32,35,32,110,111,113,97,58,32,80,84,72,49,50,51,13,10,80,101,114,109,105,115,115,105,111,110,69,114,114,111,114,58,32,91,69,114,114,110,111,32,49,51,93,32,80,101,114,109,105,115,115,105,111,110,32,100,101,110,105,101,100,58,32,39,47,117,115,114,47,115,104,97,114,101,47,112,111,115,105,116,114,111,110,47,114,101,115,111,117,114,99,101,115,47,97,112,112,47,101,120,116,101,110,115,105,111,110,115,47,112,111,115,105,116,114,111,110,45,112,121,116,104,111,110,47,112,121,116,104,111,110,95,102,105,108,101,115,47,100,101,97,99,116,105,118,97,116,101,47,122,115,104,47,101,110,118,86,97,114,115,46,116,120,116,39,13,10]]
2024-11-26 13:59:29.978 [debug] parsing data "[1m[7m%[27m[1m[0m           ```

**Comment by jonvanausdeln** [comment]
@jsbyysheng , thank you for getting back to me so quickly with the information.  We just released a new version that has better logging around this error message.  Could you please upgrade to [2024.12.0-80](https://github.com/posit-dev/positron/releases/tag/2024.12.0-80) and send what you are seeing in the console?  It should provide us more information as to what's going on .

Thank you!

**Comment by jsbyysheng** [comment]
> [@jsbyysheng](https://github.com/jsbyysheng) , thank you for getting back to me so quickly with the information. We just released a new version that has better logging around this error message. Could you please upgrade to [2024.12.0-80](https://github.com/posit-dev/positron/releases/tag/2024.12.0-80) and send what you are seeing in the console? It should provide us more information as to what's going on .
> 
> Thank you!
#### Positron and OS details:
Positron Version: 2024.12.0 build 80
Code - OSS Version: 1.93.0
Commit: c3c489641477362638b2a80d94355a86a63eeb21
Date: 2024-11-26T02:41:34.738Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-40-generic

Nothing changed, it still showed `HTTP request failed.`

**Comment by jmcphers** [comment]
It looks like the supervisor itself is not launching, based on your screenshot:

![Image](https://github.com/user-attachments/assets/a8aef266-c8e0-4f65-9603-1a458b26d099)

We need to figure out why that is. Can you first check this box:

![Image](https://github.com/user-attachments/assets/ecff34b0-62c4-4a53-a4df-f464c0bb1adc)

Then restart Positron. You should get a Terminal that shows you the failure.

If that doesn't work, could you try opening up a Terminal and manually running the `kcserver` command (with the arguments as shown in the error screenshot)? It should dump an error with more information.

**Comment by jsbyysheng** [comment]
> It looks like the supervisor itself is not launching, based on your screenshot:
> 
> ![Image](https://github.com/user-attachments/assets/a8aef266-c8e0-4f65-9603-1a458b26d099)
> 
> We need to figure out why that is. Can you first check this box:
> 
> ![Image](https://github.com/user-attachments/assets/ecff34b0-62c4-4a53-a4df-f464c0bb1adc)
> 
> Then restart Positron. You should get a Terminal that shows you the failure.
> 
> If that doesn't work, could you try opening up a Terminal and manually running the `kcserver` command (with the arguments as shown in the error screenshot)? It should dump an error with more information.

In fact, the part you cut from my screenshot comes from `Ubuntu 20.04`. In `Ubuntu 22.04`, `positron` just told me `Http request failed`.

**Comment by jmcphers** [comment]
Hmmm. The fact that your terminal doesn't show the supervisor as having _received_ any HTTP requests is interesting. Do you have any firewalls or network rules enabled on your Linux system that could be blocking it?

Can you reach the supervisor from a terminal? Try this:

```
curl http://localhost:47737/status
```

(replacing 47737 with the port shown in your Terminal tab when Positron is running)

**Comment by jsbyysheng** [comment]
> Hmmm. The fact that your terminal doesn't show the supervisor as having _received_ any HTTP requests is interesting. Do you have any firewalls or network rules enabled on your Linux system that could be blocking it?
> 
> Can you reach the supervisor from a terminal? Try this:
> 
> ```
> curl http://localhost:47737/status
> ```
> 
> (replacing 47737 with the port shown in your Terminal tab when Positron is running)

It's really wired. My computer does not enable firewall or change any rules in iptables.
![Image](https://github.com/user-attachments/assets/2ba070bd-3709-4011-92c4-ccfe5a7e9588)

**Comment by jsbyysheng** [comment]
Can any variable be set for this HTTP request timeout wait time?

**Comment by jmcphers** [comment]
No, these requests should take just a handful of milliseconds to execute since they're fully local. I've created a new version of the supervisor that has more logging to see if that will help you diagnose what's going on here; it should be available in a bit (will update when it is)

**Comment by jennybc** [comment]
@jmcphers I know I've seen some activity that looks related to extra logging. Is there anything in a release that @jsbyysheng should try out yet?

**Comment by jsbyysheng** [comment]
I am glad you have been paying attention to this issue. After further attempts, I found that the problem is related to the environment variables `http_proxy` and `https_proxy` settings. Here is the debugging process:

- Tried a new version, but it was still an HTTP request failed, and other log information remained consistent with before. 
- I recently installed [Guake Terminal](http://guake.org/), using `curl http://localhost:42425/status` in it had no output, and using `curl --dump-header - http://localhost:42425/status` prompted `502 Bad Gateway`. This was so wired.
- Then, without making any changes, directly using `curl http://localhost:42425/status` and `curl --dump-header - http://localhost:42425/status` in the system's terminal can normally obtain status and `200 OK` as the curl return value. 

Therefore, I thought of my settings for `http_proxy` and `https_proxy`. After unsetting them, `Positron` works well, and using curl in [Guake Terminal](http://guake.org/) also obtained normal return values. I've used `VSCode` for a long time without encountering this issue caused by setting up `http_proxy` or `https_proxy`. I'm wondering if this problem can be fixed? `http_proxy` and `https_proxy` is very in important for chinese users for some reasons.

**Comment by jsbyysheng** [comment]
> [@jsbyysheng](https://github.com/jsbyysheng) , unfortunately, we don't have plans at the moment to support Ubuntu 20.x
> 
> However, this should be working on Ubuntu 22, could you please provide the details you for that instance?

I wonder if you can offer a [Flathub](https://flathub.org/) version. I know that [VSCode](https://flathub.org/apps/com.visualstudio.code) has one. This would allow Ubuntu 20.x and earlier versions to use `Positron`.

**Comment by cameronbracken** [comment]
I wanted to report that I had the same problem after upgrading. I had the `http_proxy` environment variable set and was getting the "HTTP request failed" error on the console. I removed those environment variables and the console worked again.

**Comment by jmcphers** [comment]
I think the best case scenario would be for us not to use HTTP for this feature (see https://github.com/posit-dev/positron/issues/5800). 

But in lieu of that, we could make some more strategic changes:

- The `http_proxy` behavior is inherited from the [request package](https://www.npmjs.com/package/request). Currently we do not support connecting to remote supervisors (though it would be [a lot cooler if we did](https://imgur.com/gallery/d-be-lot-cooler-if-you-did-SS0dc7A)), so using a proxy is almost certain to end poorly. We could temporarily unset this variable when making API requests, or set `no_proxy` to a value that prevents a proxy from being used to talk to the local supervisor.
- The `HTTP Request Failed` error is not very helpful here. If we could show the proxy response or more detailed information, it'd help a lot.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2025.02.0-5](https://github.com/posit-dev/positron-builds/releases/tag/2025.02.0-5)
OS Version(s) : Ubuntu 24.04

### Test scenario(s) 
Setting env `http_proxy` to garbage and things work as expected.

### Link(s) to TestRail test cases run or created:
