### ISSUE TITLE
Positron kernel supervisor error in the newest version

### ISSUE THREAD

**Issue by ntluong95** [posit-dev/positron#5905]
#### Positron and OS details:

Positron Version: 2025.01.0 (system setup) build 152
Code - OSS Version: 1.95.0
Commit: 66aa3fb7f98eb8d19155cb7220856154f6ede8b3
Date: 2025-01-06T02:53:20.465Z
Electron: 32.2.1
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22621

#### Interpreter details:

R 4.4.2 and Python 3.12.4 

## Describe the issue:

![Image](https://github.com/user-attachments/assets/5d82d46f-8cd0-472c-aa5f-ed4b1042b14b)

![Image](https://github.com/user-attachments/assets/6779ecd4-423e-4d47-baf6-2ad386ab54f6)

## Were there any error messages in the UI, Output panel, or Developer Tools console?
![Image](https://github.com/user-attachments/assets/1754e5b8-eaa2-452d-958d-992c9269ba03)

```
2025-01-07 23:12:20.064 [info] Positron Kernel Supervisor activated
2025-01-07 23:12:20.064 [info] Kallichore server PID 5588 is not running
2025-01-07 23:12:20.064 [info] Could not reconnect to Kallichore server at http://localhost:64376. Starting a new server
2025-01-07 23:12:20.064 [info] Failed to start Kallichore server: Error: Kallichore server not found (expected at c:\Program Files\Positron\resources\app\extensions\positron-supervisor\resources\kallichore\kcserver.exe)
Kallichore server PID 5588 is not running
Could not reconnect to Kallichore server at http://localhost:64376. Starting a new server
Kallichore server PID 5588 is not running
Could not reconnect to Kallichore server at http://localhost:64376. Starting a new server
```

**Comment by jmcphers** [comment]
I could not reproduce this, even with a manual scan, on Windows 11, with the same Positron version. But it's possible there are different policies/settings/versions in place. You can enable an exclusion for now, and reinstall:

https://superuser.com/questions/1458660/how-to-prevent-windows-defender-antivirus-from-deleting-a-file-of-a-program

This particular false positive is a problem for many independently developed apps. :-( 

https://answers.microsoft.com/en-us/windows/forum/all/windows-defender-win32wacatacbml-false-positives/32bbe95f-2165-4559-806f-0f3386d897b7

https://answers.microsoft.com/en-us/windows/forum/all/overly-eager-heuristics-for-trojanwin32wacatacbml/6f2a72f3-3978-48ac-9fb7-fbe82c686ae3

It may be possible that there's something we can do with this binary to reduce the odds of getting flagged by Defender, but as the scan is heuristic and all the logic is owned by Microsoft it might be difficult.

See also: #5800, #5350, #5533

**Comment by ntluong95** [comment]
Thanks. I was able to restore the file and make it work. I am using a work computer so there might be some policies there from the organization. I didn't encounter this problem before

**Comment by davyzhu** [comment]
Same issue.
![Image](https://github.com/user-attachments/assets/9331b1f5-0ac2-4ab8-ab08-d19c9064b350)
![Image](https://github.com/user-attachments/assets/67bffc2a-a71d-4b4d-becb-e1f482216b87)

**Comment by lijiaqi-github** [comment]
Me too.

![Image](https://github.com/user-attachments/assets/a015c689-db51-4a19-b68f-61ee23155e93)
![Image](https://github.com/user-attachments/assets/4ede85b4-2f82-431c-9bfc-c4bc59539a9f)

**Comment by johannvk** [comment]
Same issue for me here on my first installation of Positron. Seems to work after I reverted the Windows Defender action and restored the flagged file:
![Image](https://github.com/user-attachments/assets/51f904e2-a0a1-48fd-ada9-adde2a2cf796)

**Comment by jmcphers** [comment]
Thanks all for the reports. I have opened a case with Microsoft and sent `kcserver.exe` to them to report it as a false positive. 

Depending on their response it may also be possible for us to figure out what is tripping the scanner in this version of the supervisor so we can avoid it in the future.

**Comment by e-kotov** [comment]
> I have opened a case with Microsoft and sent `kcserver.exe` to them to report it as a false positive.

@jmcphers  It's not just Microsoft. F-secure/WithSecure also quarantines it, maybe others too.

**Comment by atsyplenkov** [comment]
> Thanks all for the reports. I have opened a case with Microsoft and sent `kcserver.exe` to them to report it as a false positive.

I've encountered a similar issue with the following Positron build. Since my PC is managed by the organization, adding a new exclusion to Windows Defender isn't that straightforward for me (tbh, nearly impossible). Thanks for reporting the issue to Microsoft—it would be great if future builds could prevent this problem!

```
Positron Version: 2025.01.0 (user setup) build 152
Code - OSS Version: 1.95.0
Commit: 66aa3fb7f98eb8d19155cb7220856154f6ede8b3
Date: 2025-01-06T02:55:40.743Z
Electron: 32.2.1
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by e-kotov** [comment]
Latest Windows build ([2025.01.0-159](https://github.com/posit-dev/positron/releases/tag/2025.01.0-159)) does not get quarantined anymore, but the server does not start.

I will post the logs in the relevant issue: #5910

**Comment by juliasilge** [comment]
If we get more reports of this, we can try out #5800 as an option to mitigate these kinds of challenges with Windows machine configuration.

**Comment by e-kotov** [comment]
This issue appears again.

```
Positron Version: 2025.04.0 (user setup) build 109
Code - OSS Version: 1.97.0
Commit: 56a6c89ad24fbdeaa417ec9c03d05dbd9196c953
Date: 2025-03-17T11:54:35.787Z
Electron: 32.2.7
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.17763
```

```
Error Kallichore server did not start after 10103ms; output:
c:\Users\user1\AppData\Local\Programs\Positron\resources\app\extensions\positron-supervisor\resources\kallichore\kcserver.exe --port 56258 --token C:\Users\user1\AppData\Local\Temp\30\kallichore-fdd313e3.token --log-level debug --log-file C:\Users\user1\AppData\Local\Temp\30\kallichore-fdd313e3.log --idle-shutdown-hours 1 
```

The log is not super informative:
```
09:44:27 [INFO] Starting Kallichore server at 127.0.0.1:56258
09:44:27 [INFO] Server set to shut down after 1 hours of inactivity
```

The system has WithSecure antivirus installed, but it does not seem to be a problem, as the Kallichore server is not quarantined in this case.

Running the server manually:
```
 c:\Users\user1\AppData\Local\Programs\Positron\resources\app\extensions\positron-supervisor\resources\kallichore\kcserver.exe --port 56258
09:48:04 [INFO] Generated random auth token: 5ebeada87b88ec4e

  ,            _   _           _
 /|   /       | | | | o       | |
  |__/   __,  | | | |     __  | |     __   ,_    _
  | \   /  |  |/  |/  |  /    |/ \   /  \_/  |  |/
  |  \_/\_/|_/|__/|__/|_/\___/|   |_/\__/    |_/|__/
  A Jupyter Kernel supervisor. Version 0.1.33.
  Copyright (c) 2025, Posit Software PBC. All rights reserved.

Listening at 127.0.0.1:56258
09:48:04 [INFO] Starting Kallichore server at 127.0.0.1:56258

thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\hyper-0.14.29\src\server\server.rs:81:13:
error binding to 127.0.0.1:56258: error creating server listener: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by DDorch** [comment]
Same issue on my side with WithSecure and Positron 2025.05.0 build 142... I added an exception in WithSecure and reinstall positron and everything is fine now.

**Comment by kirk-ut** [comment]
It looks like the issue pops up again with positron `2025.06.0-167` and kallichore `0.1.42`:

![Image](https://github.com/user-attachments/assets/35159d44-5568-4aac-afd6-6b0e62437644)

**Comment by ntluong95** [comment]
The error comes again in the newest build:

Positron Version: 2025.07.0 (system setup) build 74
Code - OSS Version: 1.100.0
Commit: fe621e856f2e66144c97d30a3c77471947048e61
Date: 2025-06-09T03:58:07.136Z
Electron: 34.5.1
Chromium: 132.0.6834.210
Node.js: 20.19.0
V8: 13.2.152.41-electron.0
OS: Windows_NT x64 10.0.26200

**Comment by aphalo** [comment]
Today 2025-08-19 F-Secure Version 25.6 quarantined kcsever.exe under Windows 11. They have probably updated their heuristics, as this was new today. I restored the quarantined file and allowed the file. 

Positron Version: 2025.08.0 (system setup) build 130
Code - OSS Version: 1.102.0
Commit: 76ddce53e85437b013671fe7d91a3a1c54f48341
Date: 2025-08-01T20:25:36.785Z
Electron: 35.6.0
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Windows_NT x64 10.0.26100

**Comment by dvdkblk** [comment]
My anti-virus (Avira) also quarantined it on my Windows 11.

**Comment by ascanioalfredoa** [comment]
I had the same issue here, on a Windows 10 LTSB machine with a particular institutional policy. I kept encountering the issue even if windows defender or crowdstrike weren't flagging the kcserver.exe. In another institutional windows 11 it did run. At the end, I decided to uninstall the positron system setup and install the user-level setup. That seemed to be a workaround for now. R and Python consoles are running.

https://github.com/posit-dev/positron/issues/9379#issuecomment-3275371712

**Comment by deepoceani** [comment]
I recently have this issue as well, but it is different from the one above. 
After updating my Positron, a similar problem appeared. Since I also use R on a remote server, I changed the --idle-shutdown-hours setting from immediate to 24h. Before changing this setting, my local R/Python worked fine, but after the change, local R/Python reports a similar kcserver.exe error.
On my computer, Windows Firewall is turned off, and there is no other antivirus. I also confirmed that kcserver.exe exists in the folder, but the problem persists. 
Here is the error message, version information, and some screenshots.

R 4.5.1 failed to start.
The supervisor process exited unexpectedly during startup; output:

c:\Program Files\Positron\resources\app\extensions\positron-supervisor\resources\kallichore\kcserver.exe --log-level debug --log-file C:\Users\Deepocean\AppData\Local\Temp\kallichore-2f279e10-45696.log --connection-file C:\Users\Deepocean\AppData\Local\Temp\kallichore-2f279e10-45696.json --resource-sample-interval 1000 --transport named-pipe --idle-shutdown-hours 24 


Error: The supervisor process exited unexpectedly during startup; output:

c:\Program Files\Positron\resources\app\extensions\positron-supervisor\resources\kallichore\kcserver.exe --log-level debug --log-file C:\Users\Deepocean\AppData\Local\Temp\kallichore-2f279e10-45696.log --connection-file C:\Users\Deepocean\AppData\Local\Temp\kallichore-2f279e10-45696.json --resource-sample-interval 1000 --transport named-pipe --idle-shutdown-hours 24 

    at t.KCApi.start (c:\Program Files\Positron\resources\app\extensions\positron-supervisor\dist\extension.js:2:76393)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at listOnTimeout (node:internal/timers:549:9)
    at processTimers (node:internal/timers:523:7)

版本: Positron Version: 2026.03.0 (system setup) build 212
Code - OSS Version: 1.108.0
Commit: f3aae65e0a1a11d39226cd884520f49301daef82
Date: 2026-02-26T05:40:49.600Z
提交: 39.2.7
日期: 142.0.7444.235
Electron: 22.21.1
ElectronBuildId: 14.2.231.21-electron.0
Chromium: Windows_NT x64 10.0.22631

<img width="1337" height="303" alt="Image" src="https://github.com/user-attachments/assets/2b6aff3b-7658-4254-a673-9e333cd3fd15" />

**Comment by juliasilge** [comment]
@deepoceani Hmmm, that sounds like it might not be due to Windows security software. 

- Some folks have experienced `kcserver` instances being stuck in memory (stuck on the same ports). Can you check Task Manager for any lingering `kcserver.exe` processes and kill them?
- Does the problem go away if you revert the `--idle-shutdown-hours` setting to its default?
- Can you share the contents of the Kallichore log file when you experience this exit ( like `C:\Users\Deepocean\AppData\Local\Temp\kallichore-2f279e10-45696.log` that you see)? That might show more about what is happening.

**Comment by jmcphers** [comment]
@deepoceani Additionally, can you try reproducing in a recent daily? This sounds like an issue that might have been addressed in https://github.com/posit-dev/positron/pull/11903.

**Comment by deepoceani** [comment]
> [@deepoceani](https://github.com/deepoceani) Additionally, can you try reproducing in a recent daily? This sounds like an issue that might have been addressed in [#11903](https://github.com/posit-dev/positron/pull/11903).

Thanks for your reply , 
1. if i set -idle-shutdown-hours setting to its default , the problem go away, and anything is ok.
2. i updata positron in daily channel(版本: Positron Version: 2026.04.0 (system setup) build 192,Code - OSS Version: 1.109.2
Commit: 70308e8f2841a1754bce2694fa13e892437acb16,Date: 2026-03-20T08:01:07.404Z), the problem is still appearing.
3. the error log like "kallichore-6dc56181-21472.log" dosen't exist , just an file named "kallichore-6dc56181-21472.out.log 
" in the Temp folder. this log may not helpful
[kallichore-6dc56181-21472.out.log](https://github.com/user-attachments/files/26172963/kallichore-6dc56181-21472.out.log)
4.I can start the kcserver.exe mannually,but it also dosen't work...

this problem seems to #11903. I set kerenl Supervisor show Terminal , i saw it will start but quickly closed ,then the console show this error,  Is there any other information required?

**Comment by jmcphers** [comment]
One of the changes added in #11903 is better logging for this case! Can you send the content of the "Kernel Supervisor" logs from the Output tab? They might have some more clues about what's happening.

**Comment by deepoceani** [comment]
> One of the changes added in [#11903](https://github.com/posit-dev/positron/pull/11903) is better logging for this case! Can you send the content of the "Kernel Supervisor" logs from the Output tab? They might have some more clues about what's happening.

 There are no log in Output tab....(maybe i am not sure wherr is the "Kernel Supervisor" logs)

I revisited #11903 and also checked the supervisor-wrapper.bat file in the positron-supervisor directory.
I noticed that this issue seems to be related to how spaces in paths are handled by cmd on Windows.

So I reinstalled the latest release version (not the daily build) to the root directory of the D drive (instead of the default path C:\Program Files).

Encouragingly, the issue disappeared. I was able to change the value of the --idle-shutdown-hours option arbitrarily without triggering the problem I mentioned earlier.

I'm not entirely sure whether this issue is related to how spaces in the installation path are handled, as I mentioned earlier.
However, installing Positron in a path without spaces seems to resolve the problem.

**Comment by jmcphers** [comment]
Thank you, that's very helpful! We'll take a look and see if there's a way that could cause what you're seeing.

**Comment by christianlindell** [comment]
Windows defender flagged "extension.js" as a trojan. (C:\Users\chris\.positron\extensions\posit.assistant-0.5.9-universal\dist\extension.js) after I installed Positron build 211. I´m using Windows Home 11.

**Comment by uhkeller** [comment]
> Windows defender flagged "extension.js" as a trojan. (C:\Users\chris.positron\extensions\posit.assistant-0.5.9-universal\dist\extension.js) after I installed Positron build 211. I´m using Windows Home 11.

Same thing on macOS with Microsoft Defender (mandated by employer), also 2026.06.0 build 211.

**Comment by juliasilge** [comment]
Thank you for those reports, @christianlindell and @uhkeller! I have opened https://github.com/posit-dev/assistant-feedback/issues/16 for the Assistant team to dig into why that extension is tripping Microsoft Defender.
