### ISSUE TITLE
Multisession: pyrefly "could not find import" diagnostics not updating upon switching sessions

### ISSUE THREAD

**Issue by samclark2015** [posit-dev/positron#6936]
PR #6920 fixes Pyright diagnostics when switching sessions in an open workspace. However, the behavior does not work when not in a workspace (i.e., 'No folder opened' in the Explorer pane). 

This is likely due to [this change in the `InterpreterPathService.update()` method ](https://github.com/posit-dev/positron/blob/6e2641a491a8f716b7312738e1c5d429cade5f72/extensions/positron-python/src/client/common/interpreterPathService.ts#L114).

https://github.com/user-attachments/assets/13796ffa-4d61-469e-bbe0-d4c7088fcfcc

**Comment by juliasilge** [comment]
When we look into how to address this, we may want to consider how we handle Pyright diagnostics more holistically, perhaps looking into the new pull diagnostics as described in #6933. 

Right now IIUC we are depending on the Pyright approach of triggering on a change of the Python active interpreter. Why is `onDidChangeForegroundSession` not updating the internal "active interpreter" for the Python extension currently?

**Comment by austin3dickey** [comment]
This is still happening after switching from pyright to pyrefly.

Now the diagnostics don't update even if you're in a workspace. However, if you're in a workspace, the semantic tokens will still switch on and off.

https://github.com/user-attachments/assets/e1ac56c9-01ed-4f4b-a4c7-1eae4cd71120

**Comment by austin3dickey** [comment]
moving back to Triage - I won't be able to do this for 2025.12.0 and it doesn't seem like the hugest priority right now!

**Comment by austin3dickey** [comment]
Actually I think this is a bit higher priority; I'll pick it up early next release. It would be nice to get more LSP features for e.g. pandas if you're not in a workspace.

The cause seems to be that when pyrefly [activates](https://github.com/facebook/pyrefly/blob/29d542e7cfd491ad00a59a433cac1117352dfef9/lsp/src/extension.ts#L213), it calls the python API's `getActiveEnvironmentPath()`, which can return the wrong result in workspace-less sessions. A workaround is to do something like `echo 'python-interpreter-path = "/path/to/the/correct/python"' > $HOME/pyrefly.toml` but that's definitely not ideal.

**Comment by juliasilge** [comment]
I looked into this some today: https://github.com/posit-dev/positron/issues/6936#issuecomment-3564163932

And I think this is a problem upstream in Pyrefly. I can reproduce that problem in VS Code with Pyrefly installed

- Have two Python environments, one with a package and one without (let's say pandas)
- Have a file that imports pandas
- Use _Python: Select Interpreter_ to select the environment _without_ pandas
- Pyrefly will generate a "Could not find import of `pandas`" diagnostic
- Use _Python: Select Interpreter_ to select the environment _with_ pandas
- A bunch of LSP features update but the diagnostics do NOT refresh

I think probably the best next step for this problem is to report upstream and see if we can get that fixed.

This is separate from the "no workspace" state problems, which are lower priority IMO.

**Comment by juliasilge** [comment]
I opened https://github.com/facebook/pyrefly/issues/1767 for us to see if we can get this fixed upstream.

**Comment by juliasilge** [comment]
This should be fixed in Pyrefly 0.45.0.

**Comment by austin3dickey** [comment]
I don't see the problem anymore!

- Latest `main`
- pyrefly 0.47.0
- workspace open
- file open with `import pandas`
- have the setting `"python.pyrefly.displayTypeErrors": "force-on"` so that diagnostics are displayed
- open a session with pandas installed, and another session without
- switch between the sessions and the diagnostics toggle!

However, I still see the problem when you're not in a workspace. This is probably due to a bug in the python extension where various methods (`getActiveEnvironmentPath`, `getActiveInterpreter`, etc) don't return the correct result when you're not in a workspace. That bug was probably the cause of this original issue too.

**Comment by austin3dickey** [comment]
Note to QA for verification: we'll just verify the above works in a workspace. We'll leave the workspaceless scenario to #11281.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2026.02.0-48](https://github.com/posit-dev/positron-builds/releases/tag/2026.02.0-48)
OS Version(s) : Windows 11

### Test scenario(s) 
Workspace scenario mentioned above works as expected!
