### ISSUE TITLE
High latency with `{later}` event loop in Positron

### ISSUE THREAD

**Issue by wch** [posit-dev/positron#7235]
#### Positron and OS details:

Positron Version: 2025.05.0 (Universal) build 35
Code - OSS Version: 1.98.0
Commit: ee0feaba9d71a3e9feef765e8c3a46aeb3273741
Date: 2025-04-09T03:27:32.927Z
Electron: 34.2.0
Chromium: 132.0.6834.196
Node.js: 20.18.2
V8: 13.2.152.36-electron.0
OS: Darwin arm64 24.3.0

#### Interpreter details:

R 4.4.2

## Describe the issue:

The `later` package has an event loop that runs in the background when the R console is idle. In Positron, there seems to be very high latency in running that event loop.

`later::later()` is like JavaScript's `setTimeout()`: it schedules a function to be called at some time in the future.

With the code below, first run the top block of code, then wait for a moment, then run the last line of code:

```R
# Put these in a block to ensure they're run without delay in between.
{
  later::later(\() { finish <<- Sys.time(); cat("Finished!")}, 0)
  start <- Sys.time()
}
later::run_now()

# Wait for a moment after running block above.
# Then run:
finish - start
```

The `finish - start` will show the time between when the block of code is run, and when the callback is invoked.

When I run this in a terminal, it looks like this:

```
> {
+   later::later(\() { finish <<- Sys.time(); cat("Finished!")}, 0)
+   start <- Sys.time()
+ }
> Finished!
> finish - start
Time difference of 2.598763e-05 secs
```

The latency is .000026 seconds -- very quick.

When I run it in RStudio, it looks like this:

```
> {
+     later::later(\() { finish <<- Sys.time(); cat("Finished!")}, 0)
+     start <- Sys.time()
+ }
> 
> 
Finished!> finish - start
Time difference of 0.05610013 secs
```

Slower at .056 seconds, but it's still reasonably fast for many use cases.

With Positron:

```
> {
+   later::later(\() { finish <<- Sys.time(); cat("Finished!")}, 0)
+   start <- Sys.time()
+ }
> finish - start
Time difference of 0.2050731 secs
```

The delay here is 0.2 seconds, which is noticeably slow for many use cases.

With `later`, it is possible to run the event loop immediately by calling `run_now()`. Here's what happens when I added that after the code block and ran it in Positron:

```
> {
+   later::later(\() { finish <<- Sys.time(); cat("Finished!")}, 0)
+   start <- Sys.time()
+ }
+ later::run_now()
Finished!
> finish - start
Time difference of 7.486343e-05 secs
```

The delay is very small, at 0.00007 seconds. So the problem seems to be related to how the event loop is run when the console is idle (as opposed to running the event loop with `run_now()`).

On Unix, `later` adds an input handler to `R_InputHandlers`; that input handler runs the `later` event loop. My understanding is that the input handlers are run periodically when the console is idle. Does Positron run the input handlers at a much slower interval than the other environments?

One other issue I ran into: When the callback is run by the input handlers (as opposed to `run_now()`), the output of `cat("Finished!")` doesn't show up. I'll file another issue for that.

**Comment by juliasilge** [comment]
Maybe possibly related to #5771?

**Comment by DavisVaughan** [comment]
This seems to have gotten much better, it looks to me like we are more in line with RStudio now

```
> {
+   later::later(\() { finish <<- Sys.time(); cat("Finished!")}, 0)
+   start <- Sys.time()
+ }
Finished!
> later::run_now()
> finish - start
Time difference of 0.06631303 secs
```

I believe this is due to this commit, where @lionel- reworked this to also improve plot performance
https://github.com/posit-dev/ark/commit/452b84f459bf8777da3f03c1c6cd2ce0aec71fb2

I've opened https://github.com/posit-dev/ark/pull/836 to also add an additional note about this, so we hopefully don't rebreak it by increasing that timeout.

I'll close this once @lionel- and I verify that this was fixed by his change.

**Comment by rodrigosf672** [comment]
For me, R Studio is ~10 times faster upon running the following.
```
> {
+   later::later(\() { finish <<- Sys.time(); cat("Finished!")}, 0)
+   start <- Sys.time()
+ }
Finished!
> later::run_now()
> finish - start
```
@DavisVaughan Is that difference acceptable?
- R Studio: Time difference of 0.006410122 secs
- Positron: Time difference of 0.05975795 secs

**Comment by DavisVaughan** [comment]
You'll actually want to run it like this, without the `later::run_now()` call:

Run this chunk first

```r
# Put these in a block to ensure they're run without delay in between.
{
  later::later(\() { finish <<- Sys.time(); cat("Finished!")}, 0)
  start <- Sys.time()
}
```

Wait a second or two, then run this

```r
finish - start
```

If you do that a few times in RStudio, you should see it take around 0.05 seconds (sometimes the first time is faster for me, and in general there is some variation, but on average its around 0.05 seconds).

(BTW, when I moved this to in verification and assigned it to myself, I was planning on doing the verifying and closing, just since this is a fairly low level technical R issue that's kinda hard to test)

**Comment by rodrigosf672** [comment]
### Verified Fixed
    Positron Version(s) : 2025.07.0 (Universal) build 88
    OS Version          : Sequoia 15.5

### Test scenario(s) 
Upon running 
```
{
  later::later(\() { finish <<- Sys.time(); cat("Finished!")}, 0)
  start <- Sys.time()
}
```
and then 
``` 
finish - start
```
the following results are obtained:
- RStudio 2025.05.1+513: `Time difference of 0.05517697 secs`
- Positron 2025.07.0 (Universal) build 88: `Time difference of 0.057266 secs`

Times are almost identical, hence issue has been resolved.

**Comment by lionel-** [comment]
@rodrigosf672 Davis and I were still investigating this bug.
It's not fixed entirely, see https://github.com/posit-dev/ark/pull/836#issuecomment-2966530874

No worries though we'll track this in https://github.com/posit-dev/ark/issues/791 which should fix it for good.
Edit: oops the fix suggested in that issue will not help here.
