### ISSUE TITLE
Positron still tries to discover Python interpreters despite setting that it should be disabled

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#7445]
#### Positron and OS details:

Positron Version: 2025.05.0 (system setup) build 103
Code - OSS Version: 1.99.0
Commit: 6ea5bf42fff8529b04a6b1b9e8b0c2a7d622d54c
Date: 2025-04-28T03:48:54.330Z
Electron: 34.3.2
Chromium: 132.0.6834.210
Node.js: 20.18.3
V8: 13.2.152.41-electron.0
OS: Windows_NT x64 10.0.26100

#### Interpreter details:

R 4.5.0

## Describe the issue:

During startup, Positron still tries to find Python installations / interpreters (indicated in the lower right part of the status bar), although I have disabled this in the settings.

```
  "[python]": {
    "interpreters.startupBehavior": "disabled"
  },

```

Disabling the Python extension solves this issue, but as far as I understand, doing so [is discouraged](https://github.com/posit-dev/positron/issues/7203#issuecomment-2794180440)?

**Comment by juliasilge** [comment]
Oooof, it sounds like you are seeing https://github.com/posit-dev/positron/issues/6268 and https://github.com/posit-dev/positron/issues/7339, which we believe was fixed as of the build you have. Or maybe you mean a different part of the UI? Can you share a screenshot of what you are seeing that indicates Python discovery is happening? Is is only a status bar contribution? Or do you see Python interpreters picked up and then available to start?

We do think controlling this via settings is going to be better in the long run for users (if we can get it to actually stop!) but disabling the extension is a good workaround for now.

**Comment by strengejacke** [comment]
> Is is only a status bar contribution?

Yes, only that, I have no Python installed, so no interpreter picked up

**Comment by juliasilge** [comment]
Gotcha, thank you. I expect, based on my understanding of #7365, that discovery is _not_ actually happening but rather that the UI is telling you that it is. Thank you for the report so we can get that fixed! 🙌

**Comment by austin3dickey** [comment]
Note that (at least Python) discovery does still happen when `"interpreters.startupBehavior": "disabled"`, but then those discovered interpreters are suppressed from showing up in the UI. You can see this happening in the Python Language Pack logs, and the Python Locator logs (which is PET) if `python.locator` is `native`.

**Comment by juliasilge** [comment]
I traced this through while working on #15390. Two separate causes produce this, and both are confirmed from logs. One is in core, and one is in `positron-python`. They run at the same time, so a fix for either one alone does not remove the symptom.

An empty folder with `"[python]": { "interpreters.startupBehavior": "disabled" }` still runs a full discovery of about 40 environments in 216 ms on my machine, and still starts the `pet` server.

### Why the earlier fix looked complete

PR #7365 says it best: "Previously, it only prevented runtimes from being _discovered_. Now, it prevents runtimes from being registered _at all_, even outside the discovery phase." That change added the throw in `languageRuntime.ts:141-147`. It stops the registration, but the discovery work still runs. So the scan happens and Positron then discards the result.

### Cause 1 (core): self-discovery ignores the disabled set

`src/vs/workbench/api/common/positron/extHostLanguageRuntime.ts:1534-1547` runs a discovery pass for any runtime manager that registers after discovery is complete:

```ts
if (this._runtimeDiscoveryComplete) {
    void (async () => {
        const discoverer = manager.discoverAllRuntimes();
        for await (const runtime of discoverer) { ... }
    })();
}
```

This branch reads no disabled set. `$discoverLanguageRuntimes` honors one (`:1178`, `:1297`), so the two paths disagree. When Python is disabled, core never activates `positron-python` for runtime purposes and never waits for it. The extension still activates on its own `onStartupFinished` event, so it registers late and this branch runs. The pass reaches `discoverer.ts:46`, which calls `triggerRefresh`. Every runtime it finds is then rejected:

```
[info] [Window] Attempt to register language runtime ... (language: Python name: Python 3.10.20 (System)), but language 'python' is disabled.
[error] [Window] Cannot register 'Python 3.10.20 (System)' because the 'python' language is disabled.
```

### Cause 2 (extension): an ungated resolve at activation

`extensions/positron-python/src/client/extension.ts:169-182` schedules an interpreter refresh after activation, in every trusted workspace, with no check of the setting. It reaches the locator through `InterpreterService.refresh` -> `updateDisplay` -> `getActiveInterpreter` -> `getInterpreterDetails` -> `resolveEnv` (`legacyIOC.ts:172`) -> `finder.resolve` (`nativeAPI.ts:729`).

### Evidence that both run

In the Python Locator channel, `Resolved Python Environment <path>` comes only from `resolveImpl` (`nativePythonFinder.ts:273`), which is a direct resolve. The plain `Resolved <path>` lines come from inside `doRefresh` (`:629`). Both appear in one startup, and they overlap:

```
14:44:38.578 [info] Starting Python Locator .../python-env-tools/pet server
14:44:38.632 [info] Discovered manager: (Pyenv) /opt/homebrew/bin/pyenv
14:44:38.731 [info] Resolved Python Environment /Users/.../cpython-3.13.2-macos-aarch64-none/bin/python
14:44:38.843 [info] Refresh completed in 216ms
```

### Other ungated paths

Read from the code, not yet confirmed from logs: auto-selection (`activationManager.ts:100`), the create-environment check (`extensionActivation.ts:131`), the language server start (`languageServer/watcher.ts:136`), terminal environment activation (`terminals/envCollectionActivation/service.ts:176`), and the `**/python` watcher (`nativeAPI.ts:416`).

### Suggested direction

A gate on each call site does not converge. There are at least seven paths (!!!!!!) and they span two layers.

- For cause 1, give the self-discovery branch the same disabled set that `$discoverLanguageRuntimes` uses.
- For cause 2, add one gate at the choke point in `NativePythonFinderImpl`, so an automatic request cannot start the server while Python is disabled. An explicit request, such as a refresh from the picker, still works.

#15390 adds an `isPythonStartupDisabled()` helper and gates four eager triggers. That reduces the work but does not stop it, for the reasons above.
